Практическая работа
msenin/KotlinAndroidSFTMessenger pull request #2
Opened 2020-05-18 09:49 UTC by waleko

Сделаны все задания (1-6).
![Screenshot_1589795229](https://user-images.githubusercontent.com/24986722/82199098-ea1ee180-9905-11ea-9f2b-7b7007fba3cb.png)
![Screenshot_1589795235](https://user-images.githubusercontent.com/24986722/82199104-ed19d200-9905-11ea-8b74-4261f5af0a0a.png)
![Screenshot_1589795250](https://user-images.githubusercontent.com/24986722/82199107-ef7c2c00-9905-11ea-90a9-99f87f08604d.png)
![Screenshot_1589795266](https://user-images.githubusercontent.com/24986722/82199113-f145ef80-9905-11ea-8c9c-c8202a25e714.png)
![Screenshot_1589795286](https://user-images.githubusercontent.com/24986722/82199117-f2771c80-9905-11ea-99fb-48276979b593.png)
![Screenshot_1589795216](https://user-images.githubusercontent.com/24986722/82199119-f30fb300-9905-11ea-83b2-0cb676d390fb.png)
![Screenshot_1589795222](https://user-images.githubusercontent.com/24986722/82199123-f5720d00-9905-11ea-874b-17350fba1596.png)

2020-05-18 14:55 UTC, msenin requested changes

2020-05-18 14:55 UTC, msenin commented on app/src/main/java/ru/sft/kotlin/messenger/client/data/MessengerDao.kt
>      fun allChatsWithMembers(): LiveData<List<ChatWithMembers>>
Не очень понимаю, зачем в этом запросе Messages?
`@Relation` позволяет получать связанные сущности по внешнему ключу. 
Почему пришлось переписывать запрос?
Добавлять в ChatWithMembers Message без добавления индекса для messageId, chatId не самая удачная идея, т.к. придётся каждый раз искать максимальный messageId перебором.

2020-05-18 14:55 UTC, msenin commented on app/src/main/java/ru/sft/kotlin/messenger/client/ui/MainViewModel.kt
> +                    continue
Если currentUserChats.value == null, и isActive == true, то будет пустой цикл без всяких пауз.

2020-05-18 14:55 UTC, msenin commented on app/src/main/java/ru/sft/kotlin/messenger/client/ui/MainViewModel.kt
> +        job!!.cancelAndJoin()
лучше использовать job?.let { it.cancelAndJoin() } вместо !!

2020-05-18 14:55 UTC, msenin commented on app/src/main/java/ru/sft/kotlin/messenger/client/data/MessengerRepository.kt
> +            dao.insertUsers(*users)
Запрашивать ВСЕХ пользователей и сохранять в базе - это очень плохая идея.
1. Их может быть ну очень много
2. Они нам не нужны при поиске некоторого одного пользователя.

2020-06-05 13:32 UTC, waleko commented on app/src/main/java/ru/sft/kotlin/messenger/client/data/MessengerDao.kt
>      fun allChatsWithMembers(): LiveData<List<ChatWithMembers>>
@msenin Пришлось переписывать, потому что для `ChatWithMembers` хочется хранить последнее сообщение, чтобы оно тоже лежало в `LiveData`. Я пытался найти какой-нибудь простой способ это сделать, но получилось лишь с этим ужасным SQL запросом.

2020-12-10 14:15 UTC, merged